version: '3'
services:
  app:
    container_name: continent-service
    image: continent-service:v1
    build: .
    links:
      - redis
    ports:
      - "8080:8080"
    volumes:
      - ~/docker/continent:/continent-service/logs
  redis:
    container_name: redis
    image: redis:v1
    build: ./redis
    hostname: localhost
    ports:
      - "6379:6379"